# deployment资源
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: registry.idcos.com/common/mysql:8.0
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

# pv存储资源
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data"


# pvc存储卷
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

# service资源
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort      #这里代表是NodePort类型的
  ports:
  - port: 3306       #这里的端口和clusterIP对应，即ip:8080,供内部访问。
    targetPort: 3306  #端口一定要和container暴露出来的端口对应
    protocol: TCP
    nodePort: 30078   # 所有的节点都会开放此端口，此端口供外部调用。
  selector:
    app: mysql